/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-18 04:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BannersBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1409168812000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1409168812000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");
      out.write('\n');
 boolean hideRow1 =  kkEng.getPropertyAsBoolean("main.page.hide.banner.row1", false);
      out.write('\n');
 boolean hideRow2 =  kkEng.getPropertyAsBoolean("main.page.hide.banner.row2", false);
      out.write('\n');
      out.write('\n');
if (!hideRow1) { 
      out.write("\n");
      out.write("\t<div id=\"slideshow\"  class=\"rounded-corners\" >\n");
      out.write("\t\t");
if ((int) (Math.random() * 100) > 50) { 
      out.write("\n");
      out.write("\t\t\t<a href=\"SelectProd.action?prodId=34\">\t\t\t\t\n");
      out.write("\t\t\t\t<picture id=\"slide-1\" class=\"slide rounded-corners\">\n");
      out.write("\t\t\t\t\t<!--[if IE 9]><video style=\"display: none;\"><![endif]-->\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/kindle-fire-hd.jpg\" media=\"(min-width: 750px)\">\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/kindle-fire-hd-medium.jpg\" media=\"(min-width: 440px)\">\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/kindle-fire-hd-small.jpg\" >\n");
      out.write("\t\t\t\t\t<!--[if IE 9]></video><![endif]-->\n");
      out.write("\t\t\t\t\t<img srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/kindle-fire-hd.jpg\" alt=\"Kindle Fire HD\">\t\t\t\t\n");
      out.write("\t\t\t\t</picture>\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t<a href=\"SelectProd.action?prodId=33\">\n");
      out.write("\t\t\t\t<picture id=\"slide-1\" class=\"slide rounded-corners\">\n");
      out.write("\t\t\t\t\t<!--[if IE 9]><video style=\"display: none;\"><![endif]-->\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/delonghi.jpg\" media=\"(min-width: 750px)\">\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/delonghi-medium.png\" media=\"(min-width: 440px)\">\n");
      out.write("\t\t\t\t\t<source srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/delonghi-small.png\" >\n");
      out.write("\t\t\t\t\t<!--[if IE 9]></video><![endif]-->\n");
      out.write("\t\t\t\t\t<img srcset=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/delonghi.jpg\" alt=\"Delonghi\">\n");
      out.write("\t\t\t\t</picture>\n");
      out.write("\t\t\t</a> \n");
      out.write("\t\t");
 } 
      out.write(" \n");
      out.write("\t</div>\n");
 } 
      out.write(' ');
      out.write('\n');
      out.write('\n');
if (!hideRow2) { 
      out.write("\n");
      out.write("\t<div id=\"banners\">\n");
      out.write("\t\t<a href=\"ShowSpecials.action\"><img id=\"banner-1\" class=\"banner-small rounded-corners\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/electronics-sale.jpg\"/></a>\n");
      out.write("\t\t<a href=\"SelectCat.action?catId=24\"><img id=\"banner-2\" class=\"banner-small rounded-corners\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/gifts-for-the-home.jpg\"/></a>\n");
      out.write("\n");
      out.write("\t\t");
 if ((int) (Math.random() * 100) > 50) { 
      out.write("\n");
      out.write("\t\t<a href=\"SelectProd.action?prodId=32\"><img id=\"banner-3\" class=\"banner-small rounded-corners\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/windows-8.jpg\"/></a>\n");
      out.write("\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t<a href=\"SelectCat.action?catId=23\"><img id=\"banner-3\" class=\"banner-small rounded-corners\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/electronics-sale-2.jpg\"/></a>\n");
      out.write("\t\t");
 } 
      out.write(" \n");
      out.write("\n");
      out.write("\t\t<a href=\"SelectProd.action?prodId=35\"><img id=\"banner-4\" class=\"banner-small rounded-corners last-child\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/banners/home-page/iphone-5.jpg\"/></a>\n");
      out.write("\t</div>\n");
 } 
      out.write(" \n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
