/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-18 07:29:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import com.konakart.al.ProdOptionContainer;
import com.konakart.al.ProdOption;
import com.konakart.app.DataDescConstants;
import com.konakart.app.Option;

public final class ProductDetailsInclude_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1409168812000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1409168812000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");
      out.write('\r');
      out.write('\n');
 com.konakart.al.ProductMgr prodMgr = kkEng.getProductMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.al.ReviewMgr revMgr = kkEng.getReviewMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.ProductIf prod = prodMgr.getSelectedProduct();
      out.write('\r');
      out.write('\n');
 com.konakart.al.CustomerMgr customerMgr = kkEng.getCustomerMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.CustomerIf cust = customerMgr.getCurrentCustomer();
      out.write('\r');
      out.write('\n');
int rating = (prod.getRating()==null)?0:prod.getRating().setScale(0, java.math.BigDecimal.ROUND_HALF_UP).intValue();  
      out.write('\r');
      out.write('\n');
String ratingDecStr = (prod.getRating()==null)?"0":(prod.getRating().setScale(1, java.math.BigDecimal.ROUND_HALF_UP)).toPlainString();  
      out.write('\r');
      out.write('\n');
boolean isSmall = (kkEng.getCustomTemp1().equalsIgnoreCase("small"))?true:false;
      out.write('\r');
      out.write('\n');
String addToCartOrWishList=null; 
      out.write("\r\n");
      out.write("\t\t\t    ");
if (isSmall){
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"AddToCartOrWishListFromPost.action\" id=\"AddToCartFormSmall\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t");
 addToCartOrWishList = "addtoCartOrWishListFunc('AddToCartFormSmall')"; 
      out.write("\r\n");
      out.write("\t        \t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"AddToCartOrWishListFromPost.action\" id=\"AddToCartForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t");
 addToCartOrWishList = "addtoCartOrWishListFunc('AddToCartForm')"; 
      out.write("\r\n");
      out.write("\t        \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"random\" id=\"random\" value=\"");
      out.print(System.currentTimeMillis());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"addToWishList\" id=\"addToWishList\" class=\"addToWishList\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"prodId\" value=\"");
      out.print(prod.getId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"wishListId\" id=\"wishListId\" class=\"wishListId\" value=\"-1\" />\r\n");
      out.write("\t\t\t\t\t\t<div id=\"product-price\">\r\n");
      out.write("\t\t\t\t\t\t\t");
java.math.BigDecimal saving = null;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t    ");
if (prod.getSpecialPriceIncTax() != null){
      out.write("\r\n");
      out.write("\t\t\t\t\t                ");
saving = prod.getPriceIncTax().subtract(prod.getSpecialPriceIncTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-old\">");
      out.print(kkEng.formatPrice(prod.getPriceIncTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-current\">");
      out.print(kkEng.formatPrice(prod.getSpecialPriceIncTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t        \t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-current\">");
      out.print(kkEng.formatPrice(prod.getPriceIncTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t        \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t        ");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t            ");
if (prod.getSpecialPriceExTax() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t                ");
saving = prod.getPriceExTax().subtract(prod.getSpecialPriceExTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-old\">");
      out.print(kkEng.formatPrice(prod.getPriceExTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-current\">");
      out.print(kkEng.formatPrice(prod.getSpecialPriceExTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t        \t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t                <span class=\"product-price-current\">");
      out.print(kkEng.formatPrice(prod.getPriceExTax()));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t            ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"rating-big\">\r\n");
      out.write("\t\t\t\t            ");
if (prod.getNumberReviews()>0) {
      out.write("\r\n");
      out.write("\t\t\t\t\t            <a href='");
      out.print("SelectProd.action?prodId=" + prod.getId()+"&showRevs=t");
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t        ");
for (int i = 0; i < rating; i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t            <span class=\"star-big full\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t        ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t        ");
for (int i = rating; i < 5; i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t            <span class=\"star-big empty\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t        ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"star-reviews-link\">(");
      out.print(prod.getNumberReviews());
      out.write("&nbsp;");
      if (_jspx_meth_kk_005fmsg_005f0(_jspx_page_context))
        return;
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t            ");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        ");
for (int i = 0; i < rating; i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t            <span class=\"star-big full\"></span>\r\n");
      out.write("\t\t\t\t\t\t        ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        ");
for (int i = rating; i < 5; i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t            <span class=\"star-big empty\"></span>\r\n");
      out.write("\t\t\t\t\t\t        ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"star-reviews-link\">(");
      out.print(prod.getNumberReviews());
      out.write("&nbsp;");
      if (_jspx_meth_kk_005fmsg_005f1(_jspx_page_context))
        return;
      out.write(")</span>\r\n");
      out.write("\t\t\t\t            ");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t</div>\t\r\n");
      out.write("\t   \t\t\t\t\t");
int qtyWarn = kkEng.getStockWarnLevel();
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t");
if (prod.getQuantity() > qtyWarn){
      out.write("\r\n");
      out.write("\t\t\t\t            <div id=\"left-in-stock\">");
      if (_jspx_meth_kk_005fmsg_005f2(_jspx_page_context))
        return;
      out.write("</div>  \r\n");
      out.write("\t\t\t\t        ");
} else if (prod.getQuantity() <= qtyWarn && prod.getQuantity() > 0){
      out.write("\r\n");
      out.write("\t\t\t\t            <div id=\"left-in-stock\">");
      //  kk:msg
      com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f3 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody.get(com.konakart.kktags.MsgTag.class);
      _jspx_th_kk_005fmsg_005f3.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f3.setParent(null);
      // /WEB-INF/jsp/ProductDetailsInclude.jsp(93,40) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f3.setKey("product.details.body.limited.stock");
      // /WEB-INF/jsp/ProductDetailsInclude.jsp(93,40) name = arg0 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f3.setArg0(Integer.toString(prod.getQuantity()));
      int _jspx_eval_kk_005fmsg_005f3 = _jspx_th_kk_005fmsg_005f3.doStartTag();
      if (_jspx_th_kk_005fmsg_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005farg0_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
      out.write("</div>  \r\n");
      out.write("\t\t\t\t        ");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t            <div id=\"left-in-stock\">");
      if (_jspx_meth_kk_005fmsg_005f4(_jspx_page_context))
        return;
      out.write("</div>  \r\n");
      out.write("\t\t\t\t        ");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t<div class=\"labels\">\r\n");
      out.write("\t   \t\t\t\t\t    ");
if (prod.getType() == com.konakart.bl.ProductMgr.FREE_SHIPPING || prod.getType() == com.konakart.bl.ProductMgr.FREE_SHIPPING_BUNDLE_PRODUCT_TYPE){
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t<div class=\"label free-shipping\">");
      if (_jspx_meth_kk_005fmsg_005f5(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t   \t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t");
if (saving != null){
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t\t<div class=\"label save\">");
      if (_jspx_meth_kk_005fmsg_005f6(_jspx_page_context))
        return;
      out.write("&nbsp;");
      out.print(kkEng.formatPrice(saving));
      out.write("</div>\r\n");
      out.write("\t   \t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t</div>\t\t\r\n");
      out.write("\t   \t\t\t\t\t<div id=\"product-options\">\r\n");
      out.write("\t   \t\t\t\t\t\t");
if (prod.getOpts() != null && prod.getOpts().length > 0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 int i=0; 
      out.write("\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"product-option\">   \r\n");
      out.write("\t\t\t\t\t\t\t\t");
for (Iterator<ProdOptionContainer> iterator =  prodMgr.getSelectedProductOptions().iterator(); iterator.hasNext();) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 ProdOptionContainer optContainer =  iterator.next();
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"optionId[");
      out.print(i);
      out.write("]\" value=\"");
      out.print(optContainer.getId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"type[");
      out.print(i);
      out.write("]\" value=\"");
      out.print(optContainer.getType());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if (Integer.parseInt(optContainer.getType()) == Option.TYPE_SIMPLE){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-name\">");
      out.print(optContainer.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-value\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"valueId[");
      out.print(i);
      out.write("]\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
for (Iterator<ProdOption> iterator1 =  optContainer.getOptValues().iterator(); iterator1.hasNext();) {  
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 ProdOption option =  iterator1.next();
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t <option value=\"");
      out.print(option.getId());
      out.write('"');
      out.write('>');
      out.print(option.getFormattedValueIncTax() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(option.getId());
      out.write('"');
      out.write('>');
      out.print(option.getFormattedValueExTax() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else if (Integer.parseInt(optContainer.getType()) == Option.TYPE_VARIABLE_QUANTITY) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-name\">");
      out.print(optContainer.getName()+" ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueIncTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueExTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-value\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"numeric\" name=\"quantity[");
      out.print(i);
      out.write("]\" digits=\"true\" maxlength=\"10\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br/><span class=\"validation-msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"  name=\"valueId[");
      out.print(i);
      out.write("]\" value=\"");
      out.print( Integer.toString(optContainer.getOptValues().get(0).getId()) );
      out.write("\" />\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else if (Integer.parseInt(optContainer.getType()) == Option.TYPE_CUSTOMER_PRICE) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-name\">");
      out.print(optContainer.getName()+" ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueIncTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueExTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-value\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"numeric\" name=\"custPrice[");
      out.print(i);
      out.write("]\" number=\"true\" maxlength=\"10\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br/><span class=\"validation-msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"  name=\"valueId[");
      out.print(i);
      out.write("]\" value=\"");
      out.print( Integer.toString(optContainer.getOptValues().get(0).getId()) );
      out.write("\" />\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else if (Integer.parseInt(optContainer.getType()) == Option.TYPE_CUSTOMER_TEXT) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-name\">");
      out.print(optContainer.getName()+" ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueIncTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(optContainer.getOptValues().get(0).getFormattedValueExTax());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"opt-value\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"cust-text\" name=\"custText[");
      out.print(i);
      out.write("]\" maxlength=\"512\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br/><span class=\"validation-msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"  name=\"valueId[");
      out.print(i);
      out.write("]\" value=\"");
      out.print( Integer.toString(optContainer.getOptValues().get(0).getId()) );
      out.write("\" />\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 i++; 
      out.write("\t\t\t            \t\t\t\t            \t\t\t            \t\t\t   \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</table> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"numOptions\" value=\"");
      out.print(new Integer(i).toString());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t \t");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t</div>\t\r\n");
      out.write("\t   \t\t\t\t\t<div class=\"product-buttons\">\r\n");
      out.write("\t   \t\t\t\t\t\t<select name=\"prodQuantity\" id=\"prodQuantityId\" class=\"add-to-cart-qty\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
for (int i=1; i<31; i++) {  
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t   \t\t\t\t\t    ");
if (kkEng.getQuotaMgr().canAddToBasket(prod, null) > 0){
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t<a onmouseover=\"resetAddToWishList()\" onclick=\"");
      out.print(addToCartOrWishList);
      out.write("\" class=\"add-to-cart-button-big button small-rounded-corners\">");
      if (_jspx_meth_kk_005fmsg_005f7(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t    \t\t\t\t");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t<div class=\"add-to-wishlist-container\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t");
if (kkEng.isWishListEnabled()) { 
      out.write("\r\n");
      out.write("\t\t   \t\t\t\t\t\t\t<div class=\"add-to-wishlist-link\">\r\n");
      out.write("\t\t\t   \t\t\t\t\t\t\t<img class=\"plus-button\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/plus-button.png\"/>\r\n");
      out.write("\t\t\t   \t\t\t\t\t\t\t<a onmouseover=\"setAddToWishList()\" onclick=\"");
      out.print(addToCartOrWishList);
      out.write("\" class=\"add-to-wishlist-prod-details\">");
      if (_jspx_meth_kk_005fmsg_005f8(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (kkEng.getConfigAsBoolean("ENABLE_GIFT_REGISTRY",false) && cust.getWishLists() != null && cust.getWishLists().length > 0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for (int i = 0; i < cust.getWishLists().length; i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 com.konakart.appif.WishListIf wishList = cust.getWishLists()[i];
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (wishList != null && wishList.getListType()!= com.konakart.al.WishListMgr.WISH_LIST_TYPE ) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"add-to-wishlist-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img class=\"plus-button\" src=\"");
      out.print(kkEng.getImageBase());
      out.write("/plus-button.png\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a onmouseover='");
      out.print("setWishListId("+ new Integer(wishList.getId()).toString()+")");
      out.write("' onclick=\"");
      out.print(addToCartOrWishList);
      out.write("\" class=\"add-to-wishlist-prod-details\">");
      if (_jspx_meth_kk_005fmsg_005f9(_jspx_page_context))
        return;
      out.write("&nbsp;");
      out.print(wishList.getName());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t   \t\t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t\t</div>\t\t\t\r\n");
      out.write("   \t\t\t\t\t\t<div id=\"notify-me-container\">\r\n");
      out.write("\t   \t\t\t\t\t\t");
if (prodMgr.isCurrentProductANotification()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"ResetNotification.action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f10(_jspx_page_context))
        return;
      out.write(" <b>");
      out.print(prod.getName());
      out.write("</b> ");
      if (_jspx_meth_kk_005fmsg_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"SetNotification.action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f12(_jspx_page_context))
        return;
      out.write(" <b>");
      out.print(prod.getName());
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\r\n");
      out.write("     \t\t\t\t\t</div>  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kk_005fmsg_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f0 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f0.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f0.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(77,73) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f0.setKey("common.reviews");
    int _jspx_eval_kk_005fmsg_005f0 = _jspx_th_kk_005fmsg_005f0.doStartTag();
    if (_jspx_th_kk_005fmsg_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f1 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f1.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f1.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(86,72) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f1.setKey("common.reviews");
    int _jspx_eval_kk_005fmsg_005f1 = _jspx_th_kk_005fmsg_005f1.doStartTag();
    if (_jspx_th_kk_005fmsg_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f2 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f2.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f2.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(91,40) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f2.setKey("product.details.body.in.stock");
    int _jspx_eval_kk_005fmsg_005f2 = _jspx_th_kk_005fmsg_005f2.doStartTag();
    if (_jspx_th_kk_005fmsg_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f4 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f4.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f4.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(95,40) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f4.setKey("product.details.body.out.of.stock");
    int _jspx_eval_kk_005fmsg_005f4 = _jspx_th_kk_005fmsg_005f4.doStartTag();
    if (_jspx_th_kk_005fmsg_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f5 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f5.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f5.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(99,44) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f5.setKey("product.tile.free.shipping");
    int _jspx_eval_kk_005fmsg_005f5 = _jspx_th_kk_005fmsg_005f5.doStartTag();
    if (_jspx_th_kk_005fmsg_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f6 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f6.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f6.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(102,35) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f6.setKey("common.save");
    int _jspx_eval_kk_005fmsg_005f6 = _jspx_th_kk_005fmsg_005f6.doStartTag();
    if (_jspx_th_kk_005fmsg_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f7 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f7.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f7.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(182,144) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f7.setKey("common.add.to.cart");
    int _jspx_eval_kk_005fmsg_005f7 = _jspx_th_kk_005fmsg_005f7.doStartTag();
    if (_jspx_th_kk_005fmsg_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f8 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f8.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f8.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(188,121) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f8.setKey("common.add.to.wishlist");
    int _jspx_eval_kk_005fmsg_005f8 = _jspx_th_kk_005fmsg_005f8.doStartTag();
    if (_jspx_th_kk_005fmsg_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f9 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f9.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f9.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(197,169) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f9.setKey("product.details.body.add.product");
    int _jspx_eval_kk_005fmsg_005f9 = _jspx_th_kk_005fmsg_005f9.doStartTag();
    if (_jspx_th_kk_005fmsg_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f10 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f10.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f10.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(207,9) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f10.setKey("common.remove");
    int _jspx_eval_kk_005fmsg_005f10 = _jspx_th_kk_005fmsg_005f10.doStartTag();
    if (_jspx_th_kk_005fmsg_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f11 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f11.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f11.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(207,67) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f11.setKey("product.details.body.dontnotifyme");
    int _jspx_eval_kk_005fmsg_005f11 = _jspx_th_kk_005fmsg_005f11.doStartTag();
    if (_jspx_th_kk_005fmsg_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f12 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f12.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f12.setParent(null);
    // /WEB-INF/jsp/ProductDetailsInclude.jsp(211,9) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f12.setKey("product.details.body.notifyme");
    int _jspx_eval_kk_005fmsg_005f12 = _jspx_th_kk_005fmsg_005f12.doStartTag();
    if (_jspx_th_kk_005fmsg_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
    return false;
  }
}
