/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-18 04:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TopBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1409168812000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1409168812000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");
      out.write('\r');
      out.write('\n');
 boolean useSolr = kkEng.isUseSolr();
      out.write('\r');
      out.write('\n');
 int basketItems = kkEng.getBasketMgr().getNumberOfItems();
      out.write('\r');
      out.write('\n');
 com.konakart.al.CustomerMgr customerMgr = kkEng.getCustomerMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.CustomerIf currentCustomer = customerMgr.getCurrentCustomer();
      out.write("\r\n");
      out.write("\r\n");
int wishlistItems = 0;
      out.write('\r');
      out.write('\n');
if (currentCustomer.getWishLists() != null){
      out.write('\r');
      out.write('\n');
      out.write('	');
 for (int i = 0; i < currentCustomer.getWishLists().length; i++){ 
      out.write("\r\n");
      out.write("\t\t");
 com.konakart.appif.WishListIf wishList = currentCustomer.getWishLists()[i];
      out.write("\r\n");
      out.write("\t\t");
if (wishList.getListType()== com.konakart.al.WishListMgr.WISH_LIST_TYPE && wishList.getWishListItems()!= null){
      out.write("\r\n");
      out.write("\t\t\t");
wishlistItems = wishList.getWishListItems().length;
      out.write("\r\n");
      out.write("\t\t");
}
      out.write('\r');
      out.write('\n');
      out.write('	');
}
      out.write("\t\t\r\n");
}
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('#lang-select').selectBoxIt({\r\n");
      out.write("\t\tdownArrowIcon: \"selectboxit-down-arrow\"\r\n");
      out.write("    });\t \r\n");
      out.write("\r\n");
      out.write("\t");
if (kkEng.isPortlet()){ 
      out.write("\r\n");
      out.write("\t// Liferay hack to stop data-icon text being displayed \r\n");
      out.write("\t$('#lang-select').bind({\r\n");
      out.write("\t      \"open\": function(ev, obj) {\r\n");
      out.write("\t \t\t$('.selectboxit-option').attr('data-icon', '')\r\n");
      out.write("\t      }\t\r\n");
      out.write("\t});\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t$('#currency-select').selectBoxIt({\r\n");
      out.write("\t\tdownArrowIcon: \"selectboxit-down-arrow\"\r\n");
      out.write("    });\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    $('#open-search').click(function() {\r\n");
      out.write("        $('#slide-out-search').slideToggle('fast');\r\n");
      out.write("    });\r\n");
      out.write("    $('#close-search').click(function() {\r\n");
      out.write("        $('#slide-out-search').slideToggle('fast');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
if (useSolr) { 
      out.write("\t\r\n");
      out.write("    /* Auto complete widget */\r\n");
      out.write("    if ($( \"#search-input-mobile\" ).length != 0) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$( \"#search-input-mobile\" ).autocomplete({\r\n");
      out.write("\t\t\tsource: function(request, response) {\r\n");
      out.write("\t\t\t\tif (document.getElementById('kk_portlet_id'))  {\r\n");
      out.write("\t\t\t\t\tAUI().ready('liferay-portlet-url', function(A) { \r\n");
      out.write("\t\t\t\t        var renderURL = Liferay.PortletURL.createResourceURL();\r\n");
      out.write("\t\t\t\t        renderURL.setParameter(\"struts.portlet.action\", \"/SuggestedSearch.action\");\r\n");
      out.write("\t\t\t\t        renderURL.setPortletId(document.getElementById('kk_portlet_id').value);\r\n");
      out.write("\t\t\t\t        renderURL.setWindowState(\"exclusive\");\r\n");
      out.write("\t\t\t\t\t\trenderURL.setParameter(\"term\", request.term);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\ttimeout : '20000',\r\n");
      out.write("\t\t\t\t\t\tscriptCharset : \"utf-8\",\r\n");
      out.write("\t\t\t\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\t\t\t\turl : renderURL.toString(),\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tdata : null,\r\n");
      out.write("\t\t\t\t\t       success: function(result, textStatus, jqXHR) {\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t      \t\tresponse(result);\r\n");
      out.write("\t\t\t\t\t      }\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t});\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t     $.ajax({\r\n");
      out.write("\t\t\t\t \t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\ttimeout : '20000',\r\n");
      out.write("\t\t\t\t\t\tscriptCharset : \"utf-8\",\r\n");
      out.write("\t\t\t\t\t\tcontentType : \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t\t\t\t\turl : \"SuggestedSearch.action\",\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tdata : '{\"term\":\"' + request.term + '\"}',\r\n");
      out.write("\t\t\t\t        success: function(result, textStatus, jqXHR) {\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t       \t\tresponse(result);\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t\t     });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t   },\r\n");
      out.write("\t\t\tminLength: 1,\r\n");
      out.write("\t\t\tselect: function( event, ui ) {\r\n");
      out.write("\t\t\t\tself.kkSearch(ui.item.id,ui.item.value);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).data( \"uiAutocomplete\" )._renderItem = function( ul, item ) {\r\n");
      out.write("\t\t\t   ul.addClass('ui-corner-all');\r\n");
      out.write("\t           return $( \"<li class='ui-corner-all'></li>\" )\r\n");
      out.write("\t               .data( \"item.autocomplete\", item )\r\n");
      out.write("\t               .append( \"<a>\"+ item.label + \"</a>\" )\r\n");
      out.write("\t               .appendTo( ul );\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$(\"#search-button-mobile\").click(function (){\r\n");
      out.write("\t\t    \tvar key = document.getElementById('kk_key-mobile').value;\r\n");
      out.write("\t\t\t    var text = document.getElementById('search-input-mobile').value;\r\n");
      out.write("\t\t    \tself.kkSearch(key,text);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
 } 
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"top-bar-container\">\r\n");
      out.write("\t<div id=\"slide-out-search\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div id=\"search\">\r\n");
      out.write("\t\t\t");
if (useSolr) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t<div id=\"quickSearchFormMobile\">\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"search-input-mobile\" class=\"rounded-corners-left\" name=\"searchText\" onkeydown=\"javascript:kkKeydownMobile();\">\r\n");
      out.write("\t\t\t\t\t<input id=\"kk_key-mobile\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t\t<a id=\"search-button-mobile\" class=\"rounded-corners-right\">");
      if (_jspx_meth_kk_005fmsg_005f0(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\t\r\n");
      out.write("\t\t\t\t<form action=\"QuickSearch.action\" id=\"quickSearchFormMobile\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"true\" name=\"searchInDesc\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"search-input\" class=\"rounded-corners-left\" name=\"searchText\">\r\n");
      out.write("\t\t\t\t\t<a id=\"search-button-mobile\" class=\"rounded-corners-right\" onclick=\"javascript:document.getElementById('quickSearchFormMobile').submit();\">");
      if (_jspx_meth_kk_005fmsg_005f1(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a id=\"adv-search-link\" href=\"AdvancedSearch.action\">");
      if (_jspx_meth_kk_005fmsg_005f2(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span id=\"close-search\" class=\"fa fa-times\" title='");
      if (_jspx_meth_kk_005fmsg_005f3(_jspx_page_context))
        return;
      out.write("'></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \t<div id=\"top-bar\">\r\n");
      out.write("  \t\t<div id=\"search-container\">\r\n");
      out.write("\t  \t\t<div id=\"top-bar-search\" class=\"top-bar-menu-item\">\r\n");
      out.write("\t\t\t  \t<span id=\"open-search\" class=\"fa fa-search top-bar-menu-icon\" title=\"");
      if (_jspx_meth_kk_005fmsg_005f4(_jspx_page_context))
        return;
      out.write("\"></span> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"selections-container\">\r\n");
      out.write("\t\t\t<div id=\"selections\">\r\n");
      out.write("\t\t  \t\t<div id=\"language-selector\" class=\"top-bar-menu-item\">\r\n");
      out.write("\t\t  \t\t\t<form action=\"SetLocale.action\" method=\"post\">  \r\n");
      out.write("\t\t  \t\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"lang-select\" name=\"locale\"  onchange=\"submit()\">\r\n");
      out.write("\t\t\t\t\t\t\t<option  value=\"en_GB\" data-icon=\"flag flag-en-GB\" ");
      out.print(kkEng.getLocale().equals("en_GB")?"selected=\"selected\"":"");
      out.write(">English</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option  value=\"de_DE\" data-icon=\"flag flag-de-DE\"  ");
      out.print(kkEng.getLocale().equals("de_DE")?"selected=\"selected\"":"");
      out.write(">Deutsch</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option  value=\"es_ES\" data-icon=\"flag flag-es-ES\"  ");
      out.print(kkEng.getLocale().equals("es_ES")?"selected=\"selected\"":"");
      out.write(">Español</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option  value=\"pt_BR\" data-icon=\"flag flag-pt-BR\"  ");
      out.print(kkEng.getLocale().equals("pt_BR")?"selected=\"selected\"":"");
      out.write(">Português</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</form>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t</div>\r\n");
      out.write("\t\t  \t\t<div id=\"currency-selector\"  class=\"top-bar-menu-item\">\r\n");
      out.write("\t\t\t\t\t<form action=\"SelectCurrency.action\" method=\"post\">  \r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"currency-select\" name=\"currencyCode\"  onchange=\"submit()\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 for (int i = 0; i < kkEng.getCurrencies().length; i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 com.konakart.appif.CurrencyIf currency = kkEng.getCurrencies()[i];
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if (currency != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option  value=\"");
      out.print(currency.getCode());
      out.write('"');
      out.write('>');
      out.print(currency.getTitle());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</form>\t\t\t\t\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t  \t\t</div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t <div id=\"options-container\">\r\n");
      out.write("\t  \t\t<div id=\"options\">\t\t\r\n");
      out.write("\r\n");
      out.write("\t  \t\t");
if (kkEng.getSessionId() != null && kkEng.getSessionId().length() > 0) {
      out.write("\t\r\n");
      out.write("\t\t  \t\t<div  class=\"top-bar-menu-item\">\r\n");
      out.write("\t\t  \t\t\t<span class=\"fa fa-unlock-alt top-bar-menu-icon\"><a href=\"LogOut.action\" class=\"header2-top\" title='");
      out.print(kkEng.getMsg("header.logout.page"));
      out.write("'></a></span>\r\n");
      out.write("\t\t  \t\t\t<span class=\"top-bar-menu-title\"><a href=\"LogOut.action\" class=\"header2-top\">");
      if (_jspx_meth_kk_005fmsg_005f5(_jspx_page_context))
        return;
      out.write("</a></span>\r\n");
      out.write("\t\t  \t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<div id=\"my-account\" class=\"top-bar-menu-item\">\r\n");
      out.write("\t  \t\t\t<span class=\"fa fa-user top-bar-menu-icon\"><a href=\"LogIn.action\" title='");
      out.print(kkEng.getMsg("header.my.account"));
      out.write("'></a></span>  \t\t\t\r\n");
      out.write("\t\t  \t\t<span class=\"top-bar-menu-title\"><a href=\"LogIn.action\">");
      if (_jspx_meth_kk_005fmsg_005f6(_jspx_page_context))
        return;
      out.write("</a></span>\r\n");
      out.write("\t  \t\t\t\r\n");
      out.write("\t  \t\t</div>\r\n");
      out.write("\t  \t\t");
if (kkEng.getConfigAsBoolean("ENABLE_GIFT_REGISTRY", false)) {
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t  \t\t<div id=\"gift-registry\" class=\"top-bar-menu-item\">\t\t  \r\n");
      out.write("\t\t  \t\t\t<span class=\"fa fa-gift top-bar-menu-icon\"><a href=\"GiftRegistrySearch.action\" class=\"header2-top\" title='");
      out.print(kkEng.getMsg("header.gift.registries"));
      out.write("'></a></span> \t\t\r\n");
      out.write("\t\t  \t\t\t<span class=\"top-bar-menu-title\"><a href=\"GiftRegistrySearch.action\" class=\"header2-top\">");
      if (_jspx_meth_kk_005fmsg_005f7(_jspx_page_context))
        return;
      out.write("</a></span> \r\n");
      out.write("\t\t  \t\t</div>\t\r\n");
      out.write("\t\t\t");
}
      out.write("\t\r\n");
      out.write("\t\t\t");
if (kkEng.isWishListEnabled()) { 
      out.write("\r\n");
      out.write("\t\t  \t\t<div id=\"wish-list\" class=\"top-bar-menu-item\">\t\r\n");
      out.write("\t\t  \t\t\t<span class=\"fa fa-heart-o top-bar-menu-icon\" title='");
      if (_jspx_meth_kk_005fmsg_005f8(_jspx_page_context))
        return;
      out.write("'><span id=\"wishlist-items\">");
if (wishlistItems > 0) { 
      out.write('(');
      out.print(wishlistItems);
      out.write(")\r\n");
      out.write("\t\t\t\t");
}
      out.write("</span></span>  \t\t\t\r\n");
      out.write("\t\t  \t\t\t<span class=\"top-bar-menu-title\">");
      if (_jspx_meth_kk_005fmsg_005f9(_jspx_page_context))
        return;
      out.write("<span id=\"wishlist-items\"> ");
if (wishlistItems > 0) { 
      out.write('(');
      out.print(wishlistItems);
      out.write(")\r\n");
      out.write("\t\t\t\t");
}
      out.write("</span></span>\r\n");
      out.write("\t\t\t  \t\t \t\t\t\r\n");
      out.write("\t\t\t   \t\t<div id=\"wish-list-container\">\r\n");
      out.write("\t\t\t   \t\t<div id=\"wish-list-mouseover-shadow\" class=\"slide-out-shadow\"></div>\r\n");
      out.write("\t\t\t\t  \t<div id=\"wish-list-contents\" class=\"slide-out-contents shadow\">\t\t\t  \t\r\n");
      out.write("\t\t\t  \t\t\t");
if (wishlistItems==0){
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t<div id=\"wish-list-items\">\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t");
 com.konakart.appif.WishListIf selectedWishList = null;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (int i = 0; i < currentCustomer.getWishLists().length; i++){ 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 com.konakart.appif.WishListIf wishList = currentCustomer.getWishLists()[i];
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if (wishList.getListType()== com.konakart.al.WishListMgr.WISH_LIST_TYPE){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 selectedWishList = wishList; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (wishList.getWishListItems() != null && wishList.getWishListItems().length > 0){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 for (int j = 0; j < wishList.getWishListItems().length; j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 com.konakart.appif.WishListItemIf item = wishList.getWishListItems()[j];
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
if (item.getProduct() != null) { 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"shopping-cart-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t<a href='");
      out.print("SelectProd.action?prodId="+item.getProduct().getId());
      out.write("'><img src=\"");
      out.print(kkEng.getProdImage(item.getProduct(), com.konakart.al.KKAppEng.IMAGE_TINY));
      out.write("\" border=\"0\" alt=\"");
      out.print(item.getProduct().getName());
      out.write("\" title=\" ");
      out.print(item.getProduct().getName());
      out.write(" \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t<a href='");
      out.print("SelectProd.action?prodId="+item.getProduct().getId());
      out.write("' class=\"shopping-cart-item-title\">");
      out.print(item.getProduct().getName());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  \t\t\t\t");
      //  kk:prodOptions
      com.konakart.kktags.ProdOptionTag _jspx_th_kk_005fprodOptions_005f0 = (com.konakart.kktags.ProdOptionTag) _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.get(com.konakart.kktags.ProdOptionTag.class);
      _jspx_th_kk_005fprodOptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fprodOptions_005f0.setParent(null);
      // /WEB-INF/jsp/TopBar.jsp(232,16) name = options type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fprodOptions_005f0.setOptions(item.getOpts());
      int _jspx_eval_kk_005fprodOptions_005f0 = _jspx_th_kk_005fprodOptions_005f0.doStartTag();
      if (_jspx_th_kk_005fprodOptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.reuse(_jspx_th_kk_005fprodOptions_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.reuse(_jspx_th_kk_005fprodOptions_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t<div class=\"shopping-cart-item-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t");
if (kkEng.displayPriceWithTax()) { 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t");
      out.print(kkEng.formatPrice(item.getFinalPriceIncTax()));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t");
      out.print(kkEng.formatPrice(item.getFinalPriceExTax()));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t");
}
      out.write("\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  \t</div>\t\r\n");
      out.write("\t\t\t\t\t\t  \t<div id=\"wish-list-subtotal\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t<div class=\"subtotal\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<div class=\"subtotal-label\">");
      if (_jspx_meth_kk_005fmsg_005f11(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if (kkEng.displayPriceWithTax()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"subtotal-amount\">");
      out.print(kkEng.formatPrice(selectedWishList.getFinalPriceIncTax()));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"subtotal-amount\">");
      out.print(kkEng.formatPrice(selectedWishList.getFinalPriceExTax()));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t  \t\t");
}
      out.write("\t\t\t\t  \t\t\t\t  \t\r\n");
      out.write("\t\t\t\t  \t</div>\t\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t<div id=\"shopping-cart\" class=\"top-bar-menu-item\">\r\n");
      out.write("\t\t\t\t<span class=\"fa fa-shopping-cart top-bar-menu-icon\" title='");
      if (_jspx_meth_kk_005fmsg_005f12(_jspx_page_context))
        return;
      out.write("'><span id=\"basket-items\">");
if (basketItems > 0) { 
      out.write('(');
      out.print(basketItems);
      out.write(")\r\n");
      out.write("\t\t\t\t");
}
      out.write("</span></span>  \t\t\t\r\n");
      out.write("\t\t  \t\t<span class=\"shopping-cart-title top-bar-menu-title\">");
      if (_jspx_meth_kk_005fmsg_005f13(_jspx_page_context))
        return;
      out.write("<span id=\"basket-items\"> ");
if (basketItems > 0) {
      out.write('(');
      out.print(basketItems);
      out.write(")\r\n");
      out.write("\t\t\t\t");
}
      out.write("</span></span>\r\n");
      out.write("\t\t  \t\t\r\n");
      out.write("\t\t  \t\t\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t    <div id=\"shopping-cart-container\">\r\n");
      out.write("\t\t\t  \t<div id=\"shopping-cart-mouseover-shadow\" class=\"slide-out-shadow\"></div>\r\n");
      out.write("\t\t\t  \t<div id=\"shopping-cart-contents\" class=\"slide-out-contents shadow\">\r\n");
      out.write("\t\t\t\t\t");
if (basketItems==0 || customerMgr.getCurrentCustomer()==null || customerMgr.getCurrentCustomer().getBasketItems()==null) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_kk_005fmsg_005f14(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t<div id=\"shopping-cart-items\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for (int i = 0; i < customerMgr.getCurrentCustomer().getBasketItems().length; i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 com.konakart.appif.BasketIf item = customerMgr.getCurrentCustomer().getBasketItems()[i];
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if (item.getProduct() != null) { 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"shopping-cart-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t<a href='");
      out.print("SelectProd.action?prodId="+item.getProduct().getId());
      out.write("'><img src=\"");
      out.print(kkEng.getProdImage(item.getProduct(), com.konakart.al.KKAppEng.IMAGE_TINY));
      out.write("\" border=\"0\" alt=\"");
      out.print(item.getProduct().getName());
      out.write("\" title=\" ");
      out.print(item.getProduct().getName());
      out.write(" \"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t<a href='");
      out.print("SelectProd.action?prodId="+item.getProduct().getId());
      out.write("' class=\"shopping-cart-item-title\">");
      out.print(item.getProduct().getName());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t");
      //  kk:prodOptions
      com.konakart.kktags.ProdOptionTag _jspx_th_kk_005fprodOptions_005f1 = (com.konakart.kktags.ProdOptionTag) _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.get(com.konakart.kktags.ProdOptionTag.class);
      _jspx_th_kk_005fprodOptions_005f1.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fprodOptions_005f1.setParent(null);
      // /WEB-INF/jsp/TopBar.jsp(283,13) name = options type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fprodOptions_005f1.setOptions(item.getOpts());
      int _jspx_eval_kk_005fprodOptions_005f1 = _jspx_th_kk_005fprodOptions_005f1.doStartTag();
      if (_jspx_th_kk_005fprodOptions_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.reuse(_jspx_th_kk_005fprodOptions_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fkk_005fprodOptions_0026_005foptions_005fnobody.reuse(_jspx_th_kk_005fprodOptions_005f1);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t<div class=\"shopping-cart-item-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
if (kkEng.displayPriceWithTax()) { 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t");
      out.print(kkEng.formatPrice(item.getFinalPriceIncTax()));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t");
      out.print(kkEng.formatPrice(item.getFinalPriceExTax()));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t&nbsp;");
      if (_jspx_meth_kk_005fmsg_005f15(_jspx_page_context))
        return;
      out.write(':');
      out.print(item.getQuantity());
      out.write("\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"subtotal-and-checkout\">\r\n");
      out.write("\t\t\t\t\t  \t\t<div class=\"subtotal\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t<div class=\"subtotal-label\">");
      if (_jspx_meth_kk_005fmsg_005f16(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<div class=\"subtotal-amount\">");
      out.print(kkEng.getBasketMgr().getFormattedBasketTotal());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<div id=\"shopping-cart-checkout-button\" class=\"button small-rounded-corners\">");
      if (_jspx_meth_kk_005fmsg_005f17(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t  \t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</div>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kk_005fmsg_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f0 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f0.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f0.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(136,64) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f0.setKey("suggested.search.search");
    int _jspx_eval_kk_005fmsg_005f0 = _jspx_th_kk_005fmsg_005f0.doStartTag();
    if (_jspx_th_kk_005fmsg_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f1 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f1.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f1.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(143,144) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f1.setKey("suggested.search.search");
    int _jspx_eval_kk_005fmsg_005f1 = _jspx_th_kk_005fmsg_005f1.doStartTag();
    if (_jspx_th_kk_005fmsg_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f2 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f2.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f2.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(147,56) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f2.setKey("header.advanced.search");
    int _jspx_eval_kk_005fmsg_005f2 = _jspx_th_kk_005fmsg_005f2.doStartTag();
    if (_jspx_th_kk_005fmsg_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f3 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f3.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f3.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(149,53) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f3.setKey("common.close");
    int _jspx_eval_kk_005fmsg_005f3 = _jspx_th_kk_005fmsg_005f3.doStartTag();
    if (_jspx_th_kk_005fmsg_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f4 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f4.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f4.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(154,75) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f4.setKey("suggested.search.search");
    int _jspx_eval_kk_005fmsg_005f4 = _jspx_th_kk_005fmsg_005f4.doStartTag();
    if (_jspx_th_kk_005fmsg_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f5 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f5.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f5.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(191,84) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f5.setKey("header.logout.page");
    int _jspx_eval_kk_005fmsg_005f5 = _jspx_th_kk_005fmsg_005f5.doStartTag();
    if (_jspx_th_kk_005fmsg_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f6 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f6.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f6.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(196,62) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f6.setKey("header.my.account");
    int _jspx_eval_kk_005fmsg_005f6 = _jspx_th_kk_005fmsg_005f6.doStartTag();
    if (_jspx_th_kk_005fmsg_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f7 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f7.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f7.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(203,96) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f7.setKey("header.gift.registries");
    int _jspx_eval_kk_005fmsg_005f7 = _jspx_th_kk_005fmsg_005f7.doStartTag();
    if (_jspx_th_kk_005fmsg_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f8 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f8.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f8.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(208,60) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f8.setKey("wishlist.tile.wishlist");
    int _jspx_eval_kk_005fmsg_005f8 = _jspx_th_kk_005fmsg_005f8.doStartTag();
    if (_jspx_th_kk_005fmsg_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f9 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f9.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f9.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(210,40) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f9.setKey("wishlist.tile.wishlist");
    int _jspx_eval_kk_005fmsg_005f9 = _jspx_th_kk_005fmsg_005f9.doStartTag();
    if (_jspx_th_kk_005fmsg_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f10 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f10.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f10.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(217,9) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f10.setKey("wishlist.tile.empty");
    int _jspx_eval_kk_005fmsg_005f10 = _jspx_th_kk_005fmsg_005f10.doStartTag();
    if (_jspx_th_kk_005fmsg_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f11 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f11.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f11.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(249,39) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f11.setKey("common.subtotal");
    int _jspx_eval_kk_005fmsg_005f11 = _jspx_th_kk_005fmsg_005f11.doStartTag();
    if (_jspx_th_kk_005fmsg_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f12 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f12.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f12.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(263,63) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f12.setKey("cart.tile.shoppingcart");
    int _jspx_eval_kk_005fmsg_005f12 = _jspx_th_kk_005fmsg_005f12.doStartTag();
    if (_jspx_th_kk_005fmsg_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f13 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f13.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f13.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(265,59) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f13.setKey("cart.tile.shoppingcart");
    int _jspx_eval_kk_005fmsg_005f13 = _jspx_th_kk_005fmsg_005f13.doStartTag();
    if (_jspx_th_kk_005fmsg_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f13);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f14 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f14.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f14.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(274,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f14.setKey("cart.tile.empty");
    int _jspx_eval_kk_005fmsg_005f14 = _jspx_th_kk_005fmsg_005f14.doStartTag();
    if (_jspx_th_kk_005fmsg_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f14);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f15 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f15.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f15.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(290,20) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f15.setKey("cart.tile.quantity");
    int _jspx_eval_kk_005fmsg_005f15 = _jspx_th_kk_005fmsg_005f15.doStartTag();
    if (_jspx_th_kk_005fmsg_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f15);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f16 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f16.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f16.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(298,38) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f16.setKey("common.subtotal");
    int _jspx_eval_kk_005fmsg_005f16 = _jspx_th_kk_005fmsg_005f16.doStartTag();
    if (_jspx_th_kk_005fmsg_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f16);
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f17 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    _jspx_th_kk_005fmsg_005f17.setPageContext(_jspx_page_context);
    _jspx_th_kk_005fmsg_005f17.setParent(null);
    // /WEB-INF/jsp/TopBar.jsp(300,87) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_kk_005fmsg_005f17.setKey("common.checkout");
    int _jspx_eval_kk_005fmsg_005f17 = _jspx_th_kk_005fmsg_005f17.doStartTag();
    if (_jspx_th_kk_005fmsg_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f17);
    return false;
  }
}
