package com.konakartadmin.app;

import java.util.List;
import com.konakart.db.KKBasePeer;
import com.workingdogs.village.Record;

import com.konakartadmin.bl.KKAdmin;

/**
 * The KonaKart Custom Engine - Custom - Generated by CreateKKAdminCustomEng
 */
public class Custom
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
    public Custom(KKAdmin _kkAdminEng)
    {
        kkAdminEng = _kkAdminEng;
    }

    public String custom(String input1, String input2) throws KKAdminException
     {
        try
        {
            /*
             * Run a query that selects the orders_id of the last order processed.
             */
            List<Record> records = KKBasePeer.executeQuery("SELECT max(orders_id) FROM orders");
            if (records == null)
            {
                // No Orders Found
                return null;
            } else
            {
                return records.get(0).getValue(1).asString();
            }
        } catch (Exception e)
        {
            // TODO: handle exception
            e.printStackTrace();
            throw new KKAdminException(e);
        }
     }
}