package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddAddressesToProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddAddressesToProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddAddressesToProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addAddressesToProduct(String sessionId, AdminAddress[] addresses, int productId) throws KKAdminException
     {
         kkAdminEng.addAddressesToProduct(sessionId, addresses, productId);
     }
}
