package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCustomersToPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCustomersToPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCustomersToPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCustomersToPromotion(String sessionId, AdminCustomer[] customers, int promotionId, int rule, int maxUse) throws KKAdminException
     {
         kkAdminEng.addCustomersToPromotion(sessionId, customers, promotionId, rule, maxUse);
     }
}
