package com.konakartadmin.app;

import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCustomersToPromotionPerOrdersMade - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCustomersToPromotionPerOrdersMade
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCustomersToPromotionPerOrdersMade(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCustomersToPromotionPerOrdersMade(String sessionId, Calendar lastOrderDate, boolean havePlacedOrder, int promotionId, int rule, int maxUse) throws KKAdminException
     {
         kkAdminEng.addCustomersToPromotionPerOrdersMade(sessionId, lastOrderDate, havePlacedOrder, promotionId, rule, maxUse);
     }
}
