package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCustomerGroupsToPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCustomerGroupsToPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCustomerGroupsToPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCustomerGroupsToPromotion(String sessionId, int[] groupIds, int promotionId, int rule) throws KKAdminException
     {
         kkAdminEng.addCustomerGroupsToPromotion(sessionId, groupIds, promotionId, rule);
     }
}
