package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCouponsToPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCouponsToPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCouponsToPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCouponsToPromotion(String sessionId, AdminCoupon[] coupons, int promotionId) throws KKAdminException
     {
         kkAdminEng.addCouponsToPromotion(sessionId, coupons, promotionId);
     }
}
