package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddCategoriesToPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddCategoriesToPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddCategoriesToPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addCategoriesToPromotion(String sessionId, AdminCategory[] categories, int promotionId, int rule) throws KKAdminException
     {
         kkAdminEng.addCategoriesToPromotion(sessionId, categories, promotionId, rule);
     }
}
