package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddPanelsToRole - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddPanelsToRole
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddPanelsToRole(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addPanelsToRole(String sessionId, AdminPanel[] panels, int roleId) throws KKAdminException
     {
         kkAdminEng.addPanelsToRole(sessionId, panels, roleId);
     }
}
