package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddPromotionsToCoupon - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddPromotionsToCoupon
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddPromotionsToCoupon(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addPromotionsToCoupon(String sessionId, AdminPromotion[] promotions, int couponId) throws KKAdminException
     {
         kkAdminEng.addPromotionsToCoupon(sessionId, promotions, couponId);
     }
}
