package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddProductsToPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddProductsToPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddProductsToPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addProductsToPromotion(String sessionId, AdminProduct[] products, int promotionId, int rule) throws KKAdminException
     {
         kkAdminEng.addProductsToPromotion(sessionId, products, promotionId, rule);
     }
}
