package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddProductToSearchEngine - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddProductToSearchEngine
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddProductToSearchEngine(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addProductToSearchEngine(String sessionId, int productId) throws KKAdminException
     {
         kkAdminEng.addProductToSearchEngine(sessionId, productId);
     }
}
