package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddPoints - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddPoints
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddPoints(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int addPoints(String sessionId, int customerId, int points, String code, String description) throws KKAdminException
     {
         return kkAdminEng.addPoints(sessionId, customerId, points, code, description);
     }
}
