package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddProdAttrDescsToTemplate - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddProdAttrDescsToTemplate
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddProdAttrDescsToTemplate(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addProdAttrDescsToTemplate(String sessionId, AdminProdAttrDesc[] attrDescs, int templateId) throws KKAdminException
     {
         kkAdminEng.addProdAttrDescsToTemplate(sessionId, attrDescs, templateId);
     }
}
