package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - AddTagGroupsToCategory - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class AddTagGroupsToCategory
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public AddTagGroupsToCategory(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void addTagGroupsToCategory(String sessionId, AdminTagGroup[] tagGroups, int categoryId) throws KKAdminException
     {
         kkAdminEng.addTagGroupsToCategory(sessionId, tagGroups, categoryId);
     }
}
