package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - ChangePassword - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class ChangePassword
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public ChangePassword(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void changePassword(String sessionId, String currentPassword, String newPassword) throws KKAdminException
     {
         kkAdminEng.changePassword(sessionId, currentPassword, newPassword);
     }
}
