package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CheckSession - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CheckSession
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CheckSession(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int checkSession(String sessionId) throws KKAdminException
     {
         return kkAdminEng.checkSession(sessionId);
     }
}
