package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CheckPasswordValidity - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CheckPasswordValidity
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CheckPasswordValidity(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean checkPasswordValidity(String sessionId, String password, int userId) throws KKAdminException
     {
         return kkAdminEng.checkPasswordValidity(sessionId, password, userId);
     }
}
