package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - CopyFile - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class CopyFile
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public CopyFile(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean copyFile(String sessionId, String srcFileName, String dstFileName) throws KKAdminException
     {
         return kkAdminEng.copyFile(sessionId, srcFileName, dstFileName);
     }
}
