package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - Custom - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class Custom
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public Custom(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String custom(String input1, String input2) throws KKAdminException
     {
         return kkAdminEng.custom(input1, input2);
     }
}
