package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteExpiredSessions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteExpiredSessions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteExpiredSessions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteExpiredSessions(String sessionId) throws KKAdminException
     {
         return kkAdminEng.deleteExpiredSessions(sessionId);
     }
}
