package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProdAttrTemplate - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProdAttrTemplate
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProdAttrTemplate(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteProdAttrTemplate(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deleteProdAttrTemplate(sessionId, id);
     }
}
