package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteMiscPrices - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteMiscPrices
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteMiscPrices(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteMiscPrices(String sessionId, AdminMiscPriceSearch miscPriceSearch) throws KKAdminException
     {
         kkAdminEng.deleteMiscPrices(sessionId, miscPriceSearch);
     }
}
