package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteSpecial - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteSpecial
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteSpecial(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteSpecial(String sessionId, int specialId) throws KKAdminException
     {
         kkAdminEng.deleteSpecial(sessionId, specialId);
     }
}
