package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteOrderRefund - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteOrderRefund
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteOrderRefund(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteOrderRefund(String sessionId, int orderRefundId) throws KKAdminException
     {
         kkAdminEng.deleteOrderRefund(sessionId, orderRefundId);
     }
}
