package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProductAttributesPerProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProductAttributesPerProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProductAttributesPerProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteProductAttributesPerProduct(String sessionId, int productId) throws KKAdminException
     {
         kkAdminEng.deleteProductAttributesPerProduct(sessionId, productId);
     }
}
