package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteExpressionVariablesForExpression - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteExpressionVariablesForExpression
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteExpressionVariablesForExpression(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteExpressionVariablesForExpression(String sessionId, int expressionId) throws KKAdminException
     {
         kkAdminEng.deleteExpressionVariablesForExpression(sessionId, expressionId);
     }
}
