package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCountry - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCountry
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCountry(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteCountry(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deleteCountry(sessionId, id);
     }
}
