package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCategoryTree - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCategoryTree
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCategoryTree(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteCategoryTree(String sessionId, int categoryId, int options) throws KKAdminException
     {
         kkAdminEng.deleteCategoryTree(sessionId, categoryId, options);
     }
}
