package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteTag - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteTag
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteTag(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteTag(String sessionId, int id) throws KKAdminException
     {
         kkAdminEng.deleteTag(sessionId, id);
     }
}
