package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteAuditData - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteAuditData
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteAuditData(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteAuditData(String sessionId, AdminAuditSearch delSearch) throws KKAdminException
     {
         kkAdminEng.deleteAuditData(sessionId, delSearch);
     }
}
