package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeletePaymentSchedule - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeletePaymentSchedule
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeletePaymentSchedule(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deletePaymentSchedule(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deletePaymentSchedule(sessionId, id);
     }
}
