package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteSubZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteSubZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteSubZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteSubZone(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deleteSubZone(sessionId, id);
     }
}
