package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeletePoints - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeletePoints
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeletePoints(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deletePoints(String sessionId, int customerId, int points, String code, String description) throws KKAdminException
     {
         return kkAdminEng.deletePoints(sessionId, customerId, points, code, description);
     }
}
