package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteProduct(String sessionId, int productId) throws KKAdminException
     {
         kkAdminEng.deleteProduct(sessionId, productId);
     }
}
