package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCatalog - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCatalog
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCatalog(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteCatalog(String sessionId, int catalogId) throws KKAdminException
     {
         kkAdminEng.deleteCatalog(sessionId, catalogId);
     }
}
