package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteMallStore - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteMallStore
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteMallStore(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteMallStore(String sessionId, String storeId) throws KKAdminException
     {
         kkAdminEng.deleteMallStore(sessionId, storeId);
     }
}
