package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteCustomer(String sessionId, int custId) throws KKAdminException
     {
         return kkAdminEng.deleteCustomer(sessionId, custId);
     }
}
