package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteGeoZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteGeoZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteGeoZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteGeoZone(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deleteGeoZone(sessionId, id);
     }
}
