package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteOrder - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteOrder
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteOrder(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteOrder(String sessionId, int ordId) throws KKAdminException
     {
         return kkAdminEng.deleteOrder(sessionId, ordId);
     }
}
