package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteOrderReturn - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteOrderReturn
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteOrderReturn(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteOrderReturn(String sessionId, int orderRetId) throws KKAdminException
     {
         kkAdminEng.deleteOrderReturn(sessionId, orderRetId);
     }
}
