package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteProductOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteProductOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteProductOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteProductOptions(String sessionId, int productOptionId) throws KKAdminException
     {
         kkAdminEng.deleteProductOptions(sessionId, productOptionId);
     }
}
