package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteApiCall - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteApiCall
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteApiCall(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteApiCall(String sessionId, int apiCallId) throws KKAdminException
     {
         kkAdminEng.deleteApiCall(sessionId, apiCallId);
     }
}
