package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditOrderReturn - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditOrderReturn
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditOrderReturn(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editOrderReturn(String sessionId, AdminOrderReturn orderRet) throws KKAdminException
     {
         kkAdminEng.editOrderReturn(sessionId, orderRet);
     }
}
