package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditCategory - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditCategory
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditCategory(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editCategory(String sessionId, AdminCategory cat) throws KKAdminException
     {
         kkAdminEng.editCategory(sessionId, cat);
     }
}
