package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditSpecial - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditSpecial
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditSpecial(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editSpecial(String sessionId, AdminSpecial special) throws KKAdminException
     {
         kkAdminEng.editSpecial(sessionId, special);
     }
}
