package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditOrderShipment - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditOrderShipment
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditOrderShipment(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editOrderShipment(String sessionId, AdminOrderShipment orderShipment) throws KKAdminException
     {
         kkAdminEng.editOrderShipment(sessionId, orderShipment);
     }
}
