package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditProductAttribute - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditProductAttribute
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditProductAttribute(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editProductAttribute(String sessionId, AdminProductAttribute prodAttr) throws KKAdminException
     {
         kkAdminEng.editProductAttribute(sessionId, prodAttr);
     }
}
