package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditCoupon - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditCoupon
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditCoupon(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editCoupon(String sessionId, AdminCoupon coupon) throws KKAdminException
     {
         kkAdminEng.editCoupon(sessionId, coupon);
     }
}
