package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editPromotion(String sessionId, AdminPromotion promotion) throws KKAdminException
     {
         kkAdminEng.editPromotion(sessionId, promotion);
     }
}
