package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - EditProductWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class EditProductWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public EditProductWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void editProductWithOptions(String sessionId, AdminProduct product, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         kkAdminEng.editProductWithOptions(sessionId, product, mgrOptions);
     }
}
