package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAuditData - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAuditData
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAuditData(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminAuditSearchResult getAuditData(String sessionId, AdminAuditSearch retSearch, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getAuditData(sessionId, retSearch, offset, size);
     }
}
