package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAddressById - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAddressById
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAddressById(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminAddress getAddressById(String sessionId, int addressId) throws KKAdminException
     {
         return kkAdminEng.getAddressById(sessionId, addressId);
     }
}
