package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllOrderStatuses - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllOrderStatuses
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllOrderStatuses(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrderStatusName[] getAllOrderStatuses(int languageId) throws KKAdminException
     {
         return kkAdminEng.getAllOrderStatuses(languageId);
     }
}
