package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllAddressFormats - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllAddressFormats
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllAddressFormats(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminAddressFormat[] getAllAddressFormats() throws KKAdminException
     {
         return kkAdminEng.getAllAddressFormats();
     }
}
