package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetApiCall - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetApiCall
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetApiCall(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminApiCall getApiCall(String sessionId, int apiCallId) throws KKAdminException
     {
         return kkAdminEng.getApiCall(sessionId, apiCallId);
     }
}
