package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllConfigurationGroups - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllConfigurationGroups
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllConfigurationGroups(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminConfigurationGroup[] getAllConfigurationGroups(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getAllConfigurationGroups(sessionId);
     }
}
