package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllCountriesFull - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllCountriesFull
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllCountriesFull(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCountry[] getAllCountriesFull() throws KKAdminException
     {
         return kkAdminEng.getAllCountriesFull();
     }
}
