package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllApiCalls - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllApiCalls
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllApiCalls(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminApiCall[] getAllApiCalls(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getAllApiCalls(sessionId);
     }
}
