package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllPanels - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllPanels
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllPanels(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPanel[] getAllPanels(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getAllPanels(sessionId);
     }
}
