package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetConfigurationGroupsByTitle - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationGroupsByTitle
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetConfigurationGroupsByTitle(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminConfigurationGroup[] getConfigurationGroupsByTitle(String sessionId, String title) throws KKAdminException
     {
         return kkAdminEng.getConfigurationGroupsByTitle(sessionId, title);
     }
}
