package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerTags - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerTags
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerTags(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomerTagSearchResult getCustomerTags(String sessionId, AdminCustomerTagSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getCustomerTags(sessionId, search, offset, size);
     }
}
