package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCoupons - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCoupons
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCoupons(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCouponSearchResult getCoupons(String sessionId, AdminCouponSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getCoupons(sessionId, search, offset, size);
     }
}
