package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetConfigurationsByGroup - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationsByGroup
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetConfigurationsByGroup(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public KKConfiguration[] getConfigurationsByGroup(String sessionId, int configGroup) throws KKAdminException
     {
         return kkAdminEng.getConfigurationsByGroup(sessionId, configGroup);
     }
}
