package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerTag - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerTag
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerTag(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomerTag getCustomerTag(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.getCustomerTag(sessionId, id);
     }
}
