package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomValidatorSet - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomValidatorSet
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomValidatorSet(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomValidatorSet getCustomValidatorSet() throws KKAdminException
     {
         return kkAdminEng.getCustomValidatorSet();
     }
}
