package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomDataFromSession - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomDataFromSession
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomDataFromSession(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getCustomDataFromSession(String sessionId, int position) throws KKAdminException
     {
         return kkAdminEng.getCustomDataFromSession(sessionId, position);
     }
}
