package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerGroupsPerPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerGroupsPerPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerGroupsPerPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomerGroup[] getCustomerGroupsPerPromotion(String sessionId, int promotionId, int languageId) throws KKAdminException
     {
         return kkAdminEng.getCustomerGroupsPerPromotion(sessionId, promotionId, languageId);
     }
}
