package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCategory - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCategory
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCategory(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCategory getCategory(int categoryId, boolean getChildren, int languageId) throws KKAdminException
     {
         return kkAdminEng.getCategory(categoryId, getChildren, languageId);
     }
}
