package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomers - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomers
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomers(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomerSearchResult getCustomers(String sessionId, AdminCustomerSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getCustomers(sessionId, search, offset, size);
     }
}
