package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCurrency - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCurrency
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCurrency(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCurrency getCurrency(String currencyCode) throws KKAdminException
     {
         return kkAdminEng.getCurrency(currencyCode);
     }
}
