package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetConfigFiles - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetConfigFiles
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetConfigFiles(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminFile[] getConfigFiles(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getConfigFiles(sessionId);
     }
}
