package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCatalogs - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCatalogs
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCatalogs(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCatalogSearchResult getCatalogs(String sessionId, AdminCatalogSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getCatalogs(sessionId, search, offset, size);
     }
}
