package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCategoryTree - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCategoryTree
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCategoryTree(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCategory[] getCategoryTree(int languageId, boolean getNumProducts) throws KKAdminException
     {
         return kkAdminEng.getCategoryTree(languageId, getNumProducts);
     }
}
