package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetCustomerGroups - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerGroups
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetCustomerGroups(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminCustomerGroupSearchResult getCustomerGroups(AdminCustomerGroupSearch search) throws KKAdminException
     {
         return kkAdminEng.getCustomerGroups(search);
     }
}
