package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetConfigurationInfo - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationInfo
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetConfigurationInfo(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String[] getConfigurationInfo(String sessionId, String[] validationKeys) throws KKAdminException
     {
         return kkAdminEng.getConfigurationInfo(sessionId, validationKeys);
     }
}
