package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetDefaultLanguage - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetDefaultLanguage
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetDefaultLanguage(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminLanguage getDefaultLanguage() throws KKAdminException
     {
         return kkAdminEng.getDefaultLanguage();
     }
}
