package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetEngConf - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetEngConf
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetEngConf(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminEngineConfig getEngConf() throws KKAdminException
     {
         return kkAdminEng.getEngConf();
     }
}
