package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetExpressionForName - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetExpressionForName
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetExpressionForName(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminExpression getExpressionForName(String sessionId, String expName) throws KKAdminException
     {
         return kkAdminEng.getExpressionForName(sessionId, expName);
     }
}
