package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetExpressions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetExpressions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetExpressions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminExpressionSearchResult getExpressions(String sessionId, AdminExpressionSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getExpressions(sessionId, search, offset, size);
     }
}
