package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetFiles - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetFiles
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetFiles(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminFile[] getFiles(String sessionId, String directory, String extension) throws KKAdminException
     {
         return kkAdminEng.getFiles(sessionId, directory, extension);
     }
}
