package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetFileContentsAsByteArray - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetFileContentsAsByteArray
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetFileContentsAsByteArray(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public byte[] getFileContentsAsByteArray(String sessionId, String fileName) throws KKAdminException
     {
         return kkAdminEng.getFileContentsAsByteArray(sessionId, fileName);
     }
}
