package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetHelpMsg - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetHelpMsg
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetHelpMsg(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getHelpMsg(String msgKey, String languageCode) throws KKAdminException
     {
         return kkAdminEng.getHelpMsg(msgKey, languageCode);
     }
}
