package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetJobStatus - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetJobStatus
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetJobStatus(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminJobStatusResponse getJobStatus(String sessionId, AdminJobStatusRequest jobStatusRequest) throws KKAdminException
     {
         return kkAdminEng.getJobStatus(sessionId, jobStatusRequest);
     }
}
