package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetLanguageIdForLocale - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetLanguageIdForLocale
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetLanguageIdForLocale(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int getLanguageIdForLocale(String locale) throws KKAdminException
     {
         return kkAdminEng.getLanguageIdForLocale(locale);
     }
}
