package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetMsgValue - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetMsgValue
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetMsgValue(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getMsgValue(String key, int type, String locale) throws KKAdminException
     {
         return kkAdminEng.getMsgValue(key, type, locale);
     }
}
