package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetMiscPrices - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetMiscPrices
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetMiscPrices(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminMiscPrice[] getMiscPrices(String sessionId, AdminMiscPriceSearch miscPriceSearch) throws KKAdminException
     {
         return kkAdminEng.getMiscPrices(sessionId, miscPriceSearch);
     }
}
