package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetMallStores - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetMallStores
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetMallStores(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminStoreSearchResult getMallStores(AdminStoreSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getMallStores(search, offset, size);
     }
}
