package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetNextProductOptionId - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetNextProductOptionId
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetNextProductOptionId(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int getNextProductOptionId(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getNextProductOptionId(sessionId);
     }
}
