package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetOrderShipments - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetOrderShipments
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetOrderShipments(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrderShipmentSearchResult getOrderShipments(String sessionId, AdminOrderShipmentSearch shipSearch, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getOrderShipments(sessionId, shipSearch, offset, size);
     }
}
