package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetOrders - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetOrders
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetOrders(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrderSearchResult getOrders(String sessionId, AdminOrderSearch search, int offset, int size, int languageId) throws KKAdminException
     {
         return kkAdminEng.getOrders(sessionId, search, offset, size, languageId);
     }
}
