package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetOrderForOrderIdAndLangId - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetOrderForOrderIdAndLangId
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetOrderForOrderIdAndLangId(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrder getOrderForOrderIdAndLangId(String sessionId, int orderId, int languageId) throws KKAdminException
     {
         return kkAdminEng.getOrderForOrderIdAndLangId(sessionId, orderId, languageId);
     }
}
