package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetPanel - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetPanel
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetPanel(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPanel getPanel(String sessionId, int panelId) throws KKAdminException
     {
         return kkAdminEng.getPanel(sessionId, panelId);
     }
}
