package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductQuantityWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductQuantityWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductQuantityWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int getProductQuantityWithOptions(String sessionId, String sku, int id, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         return kkAdminEng.getProductQuantityWithOptions(sessionId, sku, id, mgrOptions);
     }
}
