package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductAttributesPerProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductAttributesPerProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductAttributesPerProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProductAttribute[] getProductAttributesPerProduct(String sessionId, int productId) throws KKAdminException
     {
         return kkAdminEng.getProductAttributesPerProduct(sessionId, productId);
     }
}
