package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPromotion getPromotion(String sessionId, int id, boolean includeCoupons, boolean includeStats) throws KKAdminException
     {
         return kkAdminEng.getPromotion(sessionId, id, includeCoupons, includeStats);
     }
}
