package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProdAttrTemplates - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProdAttrTemplates
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProdAttrTemplates(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProdAttrTemplateSearchResult getProdAttrTemplates(String sessionId, AdminProdAttrTemplateSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getProdAttrTemplates(sessionId, search, offset, size);
     }
}
