package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductCountPerAddress - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductCountPerAddress
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductCountPerAddress(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int getProductCountPerAddress(String sessionId, int addressId) throws KKAdminException
     {
         return kkAdminEng.getProductCountPerAddress(sessionId, addressId);
     }
}
