package com.konakartadmin.app;

import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductAvailability - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductAvailability
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductAvailability(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public Calendar getProductAvailability(String sessionId, String sku, int id) throws KKAdminException
     {
         return kkAdminEng.getProductAvailability(sessionId, sku, id);
     }
}
