package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductOptionValueToProductOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductOptionValueToProductOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductOptionValueToProductOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProdOptionValToProdOption[] getProductOptionValueToProductOptions(String sessionId, AdminProdOptionValToProdOption prodOptValToProdOpt) throws KKAdminException
     {
         return kkAdminEng.getProductOptionValueToProductOptions(sessionId, prodOptValToProdOpt);
     }
}
