package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductOptionsPerName - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductOptionsPerName
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductOptionsPerName(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProductOption[] getProductOptionsPerName(String sessionId, String name, int langId) throws KKAdminException
     {
         return kkAdminEng.getProductOptionsPerName(sessionId, name, langId);
     }
}
