package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductNotificationsForCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductNotificationsForCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductNotificationsForCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProductNotification[] getProductNotificationsForCustomer(String sessionId, int customerId) throws KKAdminException
     {
         return kkAdminEng.getProductNotificationsForCustomer(sessionId, customerId);
     }
}
