package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetPaymentSchedule - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentSchedule
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetPaymentSchedule(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPaymentSchedule getPaymentSchedule(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.getPaymentSchedule(sessionId, id);
     }
}
