package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProdAttrDescsForTemplates - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProdAttrDescsForTemplates
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProdAttrDescsForTemplates(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProdAttrDesc[] getProdAttrDescsForTemplates(String sessionId, AdminProdAttrTemplate[] templates) throws KKAdminException
     {
         return kkAdminEng.getProdAttrDescsForTemplates(sessionId, templates);
     }
}
