package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetPaymentSchedules - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentSchedules
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetPaymentSchedules(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPaymentScheduleSearchResult getPaymentSchedules(String sessionId, AdminPaymentScheduleSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getPaymentSchedules(sessionId, search, offset, size);
     }
}
