package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProduct getProduct(String sessionId, int productId) throws KKAdminException
     {
         return kkAdminEng.getProduct(sessionId, productId);
     }
}
