package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import java.util.Calendar;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProductAvailabilityWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProductAvailabilityWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProductAvailabilityWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public Calendar getProductAvailabilityWithOptions(String sessionId, String sku, int id, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         return kkAdminEng.getProductAvailabilityWithOptions(sessionId, sku, id, mgrOptions);
     }
}
