package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProdAttrDescsForTemplate - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProdAttrDescsForTemplate
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProdAttrDescsForTemplate(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProdAttrDesc[] getProdAttrDescsForTemplate(String sessionId, int templateId) throws KKAdminException
     {
         return kkAdminEng.getProdAttrDescsForTemplate(sessionId, templateId);
     }
}
