package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetProdAttrDesc - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetProdAttrDesc
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetProdAttrDesc(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProdAttrDesc getProdAttrDesc(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.getProdAttrDesc(sessionId, id);
     }
}
