package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetPromotionsPerCoupon - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetPromotionsPerCoupon
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetPromotionsPerCoupon(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminPromotion[] getPromotionsPerCoupon(String sessionId, int couponId) throws KKAdminException
     {
         return kkAdminEng.getPromotionsPerCoupon(sessionId, couponId);
     }
}
