package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetRewardPoints - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetRewardPoints
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetRewardPoints(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminRewardPointSearchResult getRewardPoints(String sessionId, AdminRewardPointSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getRewardPoints(sessionId, search, offset, size);
     }
}
