package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetReview - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetReview
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetReview(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminReview getReview(String sessionId, int reviewId) throws KKAdminException
     {
         return kkAdminEng.getReview(sessionId, reviewId);
     }
}
