package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetRelatedProductsWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetRelatedProductsWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetRelatedProductsWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProducts getRelatedProductsWithOptions(String sessionId, AdminDataDescriptor dataDesc, int productId, int relationType, int languageId, AdminProductMgrOptions mgrOptions) throws KKAdminException
     {
         return kkAdminEng.getRelatedProductsWithOptions(sessionId, dataDesc, productId, relationType, languageId, mgrOptions);
     }
}
