package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetRMACode - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetRMACode
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetRMACode(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getRMACode(String sessionId, int orderId) throws KKAdminException
     {
         return kkAdminEng.getRMACode(sessionId, orderId);
     }
}
