package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetReports - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetReports
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetReports(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminReport[] getReports(String sessionId) throws KKAdminException
     {
         return kkAdminEng.getReports(sessionId);
     }
}
