package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetReviews - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetReviews
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetReviews(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminReviews getReviews(String sessionId, AdminDataDescriptor dataDesc, AdminReviewSearch revSearch) throws KKAdminException
     {
         return kkAdminEng.getReviews(sessionId, dataDesc, revSearch);
     }
}
