package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSku - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSku
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSku(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String getSku(String sessionId, AdminOrderProduct orderProd) throws KKAdminException
     {
         return kkAdminEng.getSku(sessionId, orderProd);
     }
}
