package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSubZones - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSubZones
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSubZones(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminSubZoneSearchResult getSubZones(AdminSubZoneSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getSubZones(search, offset, size);
     }
}
