package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSubscriptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSubscriptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSubscriptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminSubscriptionSearchResult getSubscriptions(String sessionId, AdminSubscriptionSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getSubscriptions(sessionId, search, offset, size);
     }
}
