package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetShippers - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetShippers
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetShippers(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminShipperSearchResult getShippers(String sessionId, AdminShipperSearch search) throws KKAdminException
     {
         return kkAdminEng.getShippers(sessionId, search);
     }
}
