package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSpecialsPerCategory - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSpecialsPerCategory
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSpecialsPerCategory(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminProducts getSpecialsPerCategory(String sessionId, AdminDataDescriptor dataDesc, int categoryId, boolean searchInSubCats, int languageId) throws KKAdminException
     {
         return kkAdminEng.getSpecialsPerCategory(sessionId, dataDesc, categoryId, searchInSubCats, languageId);
     }
}
