package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSubscription - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSubscription
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSubscription(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminSubscription getSubscription(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.getSubscription(sessionId, id);
     }
}
