package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetTagGroupsPerCategory - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetTagGroupsPerCategory
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetTagGroupsPerCategory(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminTagGroup[] getTagGroupsPerCategory(String sessionId, int categoryId, int languageId) throws KKAdminException
     {
         return kkAdminEng.getTagGroupsPerCategory(sessionId, categoryId, languageId);
     }
}
