package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetTags - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetTags
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetTags(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminTagSearchResult getTags(String sessionId, AdminSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getTags(sessionId, search, offset, size);
     }
}
