package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetWishLists - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetWishLists
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetWishLists(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminWishLists getWishLists(String sessionId, AdminWishListSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.getWishLists(sessionId, search, offset, size);
     }
}
