package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetZonesById - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetZonesById
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetZonesById(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminZone[] getZonesById(int countryId) throws KKAdminException
     {
         return kkAdminEng.getZonesById(countryId);
     }
}
