package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertMiscPrices - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertMiscPrices
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertMiscPrices(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertMiscPrices(String sessionId, AdminMiscPrice[] miscPrices) throws KKAdminException
     {
         return kkAdminEng.insertMiscPrices(sessionId, miscPrices);
     }
}
