package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertProdAttrTemplate - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertProdAttrTemplate
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertProdAttrTemplate(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertProdAttrTemplate(String sessionId, AdminProdAttrTemplate template) throws KKAdminException
     {
         return kkAdminEng.insertProdAttrTemplate(sessionId, template);
     }
}
