package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertOrderReturn - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertOrderReturn
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertOrderReturn(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertOrderReturn(String sessionId, AdminOrderReturn orderRet) throws KKAdminException
     {
         return kkAdminEng.insertOrderReturn(sessionId, orderRet);
     }
}
