package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertCountry - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertCountry
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertCountry(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertCountry(String sessionId, AdminCountry country) throws KKAdminException
     {
         return kkAdminEng.insertCountry(sessionId, country);
     }
}
