package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertSubscription - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertSubscription
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertSubscription(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertSubscription(String sessionId, AdminSubscription subscription) throws KKAdminException
     {
         return kkAdminEng.insertSubscription(sessionId, subscription);
     }
}
