package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertConfigData - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertConfigData
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertConfigData(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int[] insertConfigData(String sessionId, AdminConfigData[] configs) throws KKAdminException
     {
         return kkAdminEng.insertConfigData(sessionId, configs);
     }
}
