package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertOrderShipment - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertOrderShipment
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertOrderShipment(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertOrderShipment(String sessionId, AdminOrderShipment orderShipment) throws KKAdminException
     {
         return kkAdminEng.insertOrderShipment(sessionId, orderShipment);
     }
}
