package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertProduct(String sessionId, AdminProduct product) throws KKAdminException
     {
         return kkAdminEng.insertProduct(sessionId, product);
     }
}
