package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertZone(String sessionId, AdminZone insertObj) throws KKAdminException
     {
         return kkAdminEng.insertZone(sessionId, insertObj);
     }
}
