package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertMiscItemType - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertMiscItemType
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertMiscItemType(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertMiscItemType(String sessionId, AdminMiscItemType[] miTypes) throws KKAdminException
     {
         return kkAdminEng.insertMiscItemType(sessionId, miTypes);
     }
}
