package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertProductOptionValues - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertProductOptionValues
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertProductOptionValues(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertProductOptionValues(String sessionId, AdminProductOptionValue[] productOptionValues, int productOptionId) throws KKAdminException
     {
         return kkAdminEng.insertProductOptionValues(sessionId, productOptionValues, productOptionId);
     }
}
