package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertAddress - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertAddress
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertAddress(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertAddress(String sessionId, AdminAddress address) throws KKAdminException
     {
         return kkAdminEng.insertAddress(sessionId, address);
     }
}
