package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertPromotion(String sessionId, AdminPromotion prom) throws KKAdminException
     {
         return kkAdminEng.insertPromotion(sessionId, prom);
     }
}
