package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertProductNotification - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertProductNotification
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertProductNotification(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void insertProductNotification(String sessionId, AdminProductNotification apn) throws KKAdminException
     {
         kkAdminEng.insertProductNotification(sessionId, apn);
     }
}
