package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertOrderRefund - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertOrderRefund
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertOrderRefund(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertOrderRefund(String sessionId, AdminOrderRefund orderRefund) throws KKAdminException
     {
         return kkAdminEng.insertOrderRefund(sessionId, orderRefund);
     }
}
