package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertApiCall - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertApiCall
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertApiCall(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertApiCall(String sessionId, AdminApiCall apiCall) throws KKAdminException
     {
         return kkAdminEng.insertApiCall(sessionId, apiCall);
     }
}
