package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertConfiguration - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertConfiguration
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertConfiguration(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertConfiguration(String sessionId, KKConfiguration config) throws KKAdminException
     {
         return kkAdminEng.insertConfiguration(sessionId, config);
     }
}
