package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertCustomerGroups - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertCustomerGroups
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertCustomerGroups(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertCustomerGroups(String sessionId, AdminCustomerGroup[] custGroups) throws KKAdminException
     {
         return kkAdminEng.insertCustomerGroups(sessionId, custGroups);
     }
}
