package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertSubZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertSubZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertSubZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertSubZone(String sessionId, AdminSubZone insertObj) throws KKAdminException
     {
         return kkAdminEng.insertSubZone(sessionId, insertObj);
     }
}
