package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertOrderStatusName - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertOrderStatusName
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertOrderStatusName(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertOrderStatusName(String sessionId, AdminOrderStatusName obj) throws KKAdminException
     {
         return kkAdminEng.insertOrderStatusName(sessionId, obj);
     }
}
