package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertProductsOptionsValuesToProductsOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertProductsOptionsValuesToProductsOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertProductsOptionsValuesToProductsOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertProductsOptionsValuesToProductsOptions(String sessionId, AdminProdOptionValToProdOption prodOptValToProdOpt) throws KKAdminException
     {
         return kkAdminEng.insertProductsOptionsValuesToProductsOptions(sessionId, prodOptValToProdOpt);
     }
}
