package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertPanel - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertPanel
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertPanel(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertPanel(String sessionId, AdminPanel panel) throws KKAdminException
     {
         return kkAdminEng.insertPanel(sessionId, panel);
     }
}
