package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertGeoZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertGeoZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertGeoZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertGeoZone(String sessionId, AdminGeoZone insertObj) throws KKAdminException
     {
         return kkAdminEng.insertGeoZone(sessionId, insertObj);
     }
}
