package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertCatalog - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertCatalog
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertCatalog(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertCatalog(String sessionId, AdminCatalog catalog) throws KKAdminException
     {
         return kkAdminEng.insertCatalog(sessionId, catalog);
     }
}
