package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertManufacturer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertManufacturer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertManufacturer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertManufacturer(String sessionId, AdminManufacturer manu) throws KKAdminException
     {
         return kkAdminEng.insertManufacturer(sessionId, manu);
     }
}
