package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertTagGroup - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertTagGroup
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertTagGroup(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertTagGroup(String sessionId, AdminTagGroup tagGroup) throws KKAdminException
     {
         return kkAdminEng.insertTagGroup(sessionId, tagGroup);
     }
}
