package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertShipper - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertShipper
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertShipper(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertShipper(String sessionId, AdminShipper shipper) throws KKAdminException
     {
         return kkAdminEng.insertShipper(sessionId, shipper);
     }
}
