package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertCurrency - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertCurrency
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertCurrency(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertCurrency(String sessionId, AdminCurrency curr) throws KKAdminException
     {
         return kkAdminEng.insertCurrency(sessionId, curr);
     }
}
