package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - Login - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class Login
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public Login(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public String login(String user, String password) throws KKAdminException
     {
         return kkAdminEng.login(user, password);
     }
}
