package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - Logout - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class Logout
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public Logout(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void logout(String sessionId) throws KKAdminException
     {
         kkAdminEng.logout(sessionId);
     }
}
