package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - PointsAvailable - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class PointsAvailable
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public PointsAvailable(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int pointsAvailable(String sessionId, int customerId) throws KKAdminException
     {
         return kkAdminEng.pointsAvailable(sessionId, customerId);
     }
}
