package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RegisterCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RegisterCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RegisterCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int registerCustomer(String sessionId, AdminCustomerRegistration custReg) throws KKAdminException
     {
         return kkAdminEng.registerCustomer(sessionId, custReg);
     }
}
