package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - ReloadReports - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class ReloadReports
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public ReloadReports(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void reloadReports(String sessionId) throws KKAdminException
     {
         kkAdminEng.reloadReports(sessionId);
     }
}
