package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveProductFromCatalog - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveProductFromCatalog
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveProductFromCatalog(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeProductFromCatalog(String sessionId, int productId, String catalogId) throws KKAdminException
     {
         kkAdminEng.removeProductFromCatalog(sessionId, productId, catalogId);
     }
}
