package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveAllProductsFromSearchEngine - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveAllProductsFromSearchEngine
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveAllProductsFromSearchEngine(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeAllProductsFromSearchEngine(String sessionId, boolean async) throws KKAdminException
     {
         kkAdminEng.removeAllProductsFromSearchEngine(sessionId, async);
     }
}
