package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveExpressionsFromPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveExpressionsFromPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveExpressionsFromPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeExpressionsFromPromotion(String sessionId, AdminExpression[] expressions, int promotionId) throws KKAdminException
     {
         kkAdminEng.removeExpressionsFromPromotion(sessionId, expressions, promotionId);
     }
}
