package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveApiCallsFromRole - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveApiCallsFromRole
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveApiCallsFromRole(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeApiCallsFromRole(String sessionId, AdminApiCall[] apiCalls, int roleId) throws KKAdminException
     {
         kkAdminEng.removeApiCallsFromRole(sessionId, apiCalls, roleId);
     }
}
