package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveConfigData - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveConfigData
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveConfigData(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeConfigData(String sessionId, int id) throws KKAdminException
     {
         kkAdminEng.removeConfigData(sessionId, id);
     }
}
