package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveCustomerGroupsFromPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveCustomerGroupsFromPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveCustomerGroupsFromPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeCustomerGroupsFromPromotion(String sessionId, int[] groupIds, int promotionId) throws KKAdminException
     {
         kkAdminEng.removeCustomerGroupsFromPromotion(sessionId, groupIds, promotionId);
     }
}
