package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemovePromotionsFromCoupon - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemovePromotionsFromCoupon
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemovePromotionsFromCoupon(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removePromotionsFromCoupon(String sessionId, AdminPromotion[] promotions, int couponId) throws KKAdminException
     {
         kkAdminEng.removePromotionsFromCoupon(sessionId, promotions, couponId);
     }
}
