package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveCategoriesFromPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveCategoriesFromPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveCategoriesFromPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeCategoriesFromPromotion(String sessionId, AdminCategory[] categories, int promotionId) throws KKAdminException
     {
         kkAdminEng.removeCategoriesFromPromotion(sessionId, categories, promotionId);
     }
}
