package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveProductsFromPromotion - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveProductsFromPromotion
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveProductsFromPromotion(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeProductsFromPromotion(String sessionId, AdminProduct[] products, int promotionId) throws KKAdminException
     {
         kkAdminEng.removeProductsFromPromotion(sessionId, products, promotionId);
     }
}
