package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveProductsToStores - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveProductsToStores
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveProductsToStores(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeProductsToStores(String sessionId, AdminProductToStore[] productToStores) throws KKAdminException
     {
         kkAdminEng.removeProductsToStores(sessionId, productToStores);
     }
}
