package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveRelatedProducts - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveRelatedProducts
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveRelatedProducts(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeRelatedProducts(String sessionId, int productId, int relationType) throws KKAdminException
     {
         kkAdminEng.removeRelatedProducts(sessionId, productId, relationType);
     }
}
