package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RunBatchJob - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RunBatchJob
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RunBatchJob(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public boolean runBatchJob(String sessionId, String group, String name, String[] paramArray) throws KKAdminException
     {
         return kkAdminEng.runBatchJob(sessionId, group, name, paramArray);
     }
}
