package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SaveConfigs - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SaveConfigs
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SaveConfigs(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void saveConfigs(String sessionId, KKConfiguration[] configs, KKConfiguration[] origConfigs) throws KKAdminException
     {
         kkAdminEng.saveConfigs(sessionId, configs, origConfigs);
     }
}
