package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SearchDigitalDownloads - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SearchDigitalDownloads
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SearchDigitalDownloads(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminDigitalDownloadSearchResult searchDigitalDownloads(String sessionId, AdminDigitalDownloadSearch search, int offset, int size) throws KKAdminException
     {
         return kkAdminEng.searchDigitalDownloads(sessionId, search, offset, size);
     }
}
