package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SendTemplateEmailToCustomers1WithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SendTemplateEmailToCustomers1WithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SendTemplateEmailToCustomers1WithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void sendTemplateEmailToCustomers1WithOptions(String sessionId, AdminCustomerSearch custSearch, String templateName, String message, AdminProduct[] products, AdminOrder[] orders, AdminManufacturer[] manufacturers, AdminCategory[] categories, int numEmailThreads, AdminEmailOptions options) throws KKAdminException
     {
         kkAdminEng.sendTemplateEmailToCustomers1WithOptions(sessionId, custSearch, templateName, message, products, orders, manufacturers, categories, numEmailThreads, options);
     }
}
