package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SetCustomerPassword - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SetCustomerPassword
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SetCustomerPassword(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void setCustomerPassword(String sessionId, int custId, String newPassword) throws KKAdminException
     {
         kkAdminEng.setCustomerPassword(sessionId, custId, newPassword);
     }
}
