package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SetCreditCardDetailsOnOrder - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SetCreditCardDetailsOnOrder
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SetCreditCardDetailsOnOrder(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void setCreditCardDetailsOnOrder(String sessionId, AdminCreditCard creditCard) throws KKAdminException
     {
         kkAdminEng.setCreditCardDetailsOnOrder(sessionId, creditCard);
     }
}
