package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - SetEndpoint - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class SetEndpoint
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public SetEndpoint(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void setEndpoint(String wsEndpoint) throws KKAdminException
     {
         kkAdminEng.setEndpoint(wsEndpoint);
     }
}
