package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateOrder - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateOrder
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateOrder(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateOrder(String sessionId, int orderId, int orderStatus, String comments, boolean notifyCustomer, AdminOrderUpdate updateOrder) throws KKAdminException
     {
         kkAdminEng.updateOrder(sessionId, orderId, orderStatus, comments, notifyCustomer, updateOrder);
     }
}
