package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateCatalog - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateCatalog
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateCatalog(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateCatalog(String sessionId, AdminCatalog catalog) throws KKAdminException
     {
         kkAdminEng.updateCatalog(sessionId, catalog);
     }
}
