package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateCachedConfigurations - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateCachedConfigurations
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateCachedConfigurations(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateCachedConfigurations(String sessionId) throws KKAdminException
     {
         kkAdminEng.updateCachedConfigurations(sessionId);
     }
}
