package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateMiscItemType - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateMiscItemType
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateMiscItemType(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateMiscItemType(String sessionId, AdminMiscItemType[] miTypes) throws KKAdminException
     {
         kkAdminEng.updateMiscItemType(sessionId, miTypes);
     }
}
