package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateProdAttrDesc - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateProdAttrDesc
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateProdAttrDesc(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int updateProdAttrDesc(String sessionId, AdminProdAttrDesc attrDesc) throws KKAdminException
     {
         return kkAdminEng.updateProdAttrDesc(sessionId, attrDesc);
     }
}
