package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateLanguage - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateLanguage
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateLanguage(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int updateLanguage(String sessionId, AdminLanguage lang) throws KKAdminException
     {
         return kkAdminEng.updateLanguage(sessionId, lang);
     }
}
