package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateGeoZone - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateGeoZone
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateGeoZone(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int updateGeoZone(String sessionId, AdminGeoZone updateObj) throws KKAdminException
     {
         return kkAdminEng.updateGeoZone(sessionId, updateObj);
     }
}
