package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateAddress - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateAddress
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateAddress(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateAddress(String sessionId, AdminAddress address) throws KKAdminException
     {
         kkAdminEng.updateAddress(sessionId, address);
     }
}
