package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void updateCustomer(String sessionId, AdminCustomer customer) throws KKAdminException
     {
         kkAdminEng.updateCustomer(sessionId, customer);
     }
}
